default:
  tags:
    - vm

variables:
  PYREQUIREMENTS: requirements.txt

include:
  - file: /common.yml
    project: QubesOS/qubes-continuous-integration

stages:
  - checks
  - build

lint:
  extends: .lint
  variables:
    DIR: qubesmirror

legacy:
  stage: build
  script:
    - python3 setup.py build

python-build:
  stage: build
  before_script:
    - sudo dnf install -y python3-build
  script:
    - python3 -m build
